using SupplyShield.Domain.Enums;

namespace SupplyShield.Domain.Entities;

/// <summary>
/// A ranked recovery recommendation generated by backend intelligence services.
/// Requires explicit operator approval before any action is applied.
/// </summary>
public class RecoveryRecommendation
{
    public Guid Id { get; set; }
    public Guid ShipmentId { get; set; }
    public RecommendationType RecommendationType { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Rationale { get; set; } = string.Empty;
    public SeverityLevel Severity { get; set; }

    /// <summary>Evidence confidence 0.0–1.0. Separate from severity.</summary>
    public decimal? Confidence { get; set; }

    public Guid? ProposedRouteId { get; set; }
    public string? ProposedCarrierCode { get; set; }
    public Guid? ProposedVehicleId { get; set; }
    public int? EstimatedTimeSavingMinutes { get; set; }
    public decimal? EstimatedCostDeltaUsd { get; set; }

    /// <summary>Always true — consequential actions require human approval.</summary>
    public bool RequiresApproval { get; set; } = true;

    public DateTime CreatedAtUtc { get; set; }

    // Navigation
    public Shipment Shipment { get; set; } = null!;
}
