/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#30353d",
        "bg-surface-raised": "#141d29",
        "risk-low": "#22c55e",
        "surface-container-lowest": "#090e16",
        "risk-medium": "#f59e0b",
        "on-secondary-fixed": "#131c28",
        "on-surface-variant": "#c3c6d7",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#30353d",
        "surface-tint": "#b3c5ff",
        "secondary-container": "#3e4755",
        "tertiary-container": "#6a778b",
        "primary": "#b3c5ff",
        "border-subtle": "#243142",
        "secondary": "#bec7d7",
        "on-surface": "#dee2ed",
        "text-secondary": "#a8b3c2",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#171c23",
        "bg-surface": "#101722",
        "on-primary": "#002a76",
        "on-background": "#dee2ed",
        "on-secondary": "#28313e",
        "surface-dim": "#0f141b",
        "primary-fixed-dim": "#b3c5ff",
        "tertiary": "#bac7dd",
        "background": "#0f141b",
        "outline-variant": "#424655",
        "inverse-surface": "#dee2ed",
        "on-primary-fixed": "#00174a",
        "primary-hover": "#4a7ff7",
        "error-container": "#93000a",
        "surface": "#0f141b",
        "bg-surface-hover": "#192333",
        "risk-high": "#f97316",
        "bg-sidebar": "#0b111a",
        "primary-soft": "rgba(47, 109, 246, 0.16)",
        "inverse-on-surface": "#2c3139",
        "on-tertiary": "#243142",
        "primary-fixed": "#dbe1ff",
        "text-muted": "#6f7d8f",
        "on-tertiary-fixed": "#0f1c2c",
        "on-tertiary-fixed-variant": "#3b485a",
        "primary-container": "#2f6df6",
        "on-secondary-container": "#adb6c6",
        "bg-app": "#080d14",
        "tertiary-fixed": "#d6e3fa",
        "tertiary-fixed-dim": "#bac7dd",
        "secondary-fixed-dim": "#bec7d7",
        "surface-container-high": "#252a32",
        "text-disabled": "#4b5868",
        "on-secondary-fixed-variant": "#3e4755",
        "inverse-primary": "#0054d8",
        "risk-critical": "#ef4444",
        "on-primary-fixed-variant": "#003ea6",
        "on-error": "#690005",
        "border-strong": "#334155",
        "secondary-fixed": "#dae3f4",
        "status-info": "#38bdf8",
        "surface-bright": "#343942",
        "text-primary": "#f3f6fa",
        "on-primary-container": "#ffffff",
        "error": "#ffb4ab",
        "surface-container": "#1b2027",
        "outline": "#8d90a0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-lg": "1rem",
        gutter: "0.75rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "1.5rem",
        margin: "1.25rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "page-title": ["Inter", "sans-serif"],
        "table-cell": ["Inter", "sans-serif"],
        "section-title": ["Inter", "sans-serif"],
        "card-title": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-default": ["Inter", "sans-serif"],
        "kpi-val": ["Inter", "sans-serif"],
        "badge-label": ["Inter", "sans-serif"],
      },
      fontSize: {
        "page-title": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "table-cell": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "section-title": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "card-title": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-default": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "kpi-val": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "badge-label": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
